<head>
	<meta charset="utf-8">
	<title>个人主页--未登录</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="../css/home.css">
	<script type="text/javascript">		
		var deviceWidth = document.documentElement.clientWidth;
        if(deviceWidth > 640) deviceWidth = 640;
        document.documentElement.style.fontSize = deviceWidth / 6.4 + 'px';
	</script>
	<script type="text/javascript" src="../js/home.js"></script>

</head>