<head>
	<title>商城首页</title>
	
    <meta charset="utf-8">
	<meta name="keywors" content="aa,ca,aad,ddd">
	<meta name="description" content="">
	
	<meta name="format-detection" content="telephone=no">
    <meta name="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="" content="">
	<!-- 5秒自动跳转到百度
	<meta http-equiv="Refresh" content="5;url=http://baidu.com"> -->
	
	<meta content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0,user-scalable=no" name="viewport" id="viewport" />

	<link rel="stylesheet" href="../css/index.css">
	<script type="text/javascript">		
		var deviceWidth = document.documentElement.clientWidth;
        if(deviceWidth > 640) deviceWidth = 640;
        document.documentElement.style.fontSize = deviceWidth / 6.4 + 'px';
	</script>
	<script type="text/javascript" src="../js/index.js"></script>
</head>